### ISSUE TITLE
Fix or remove 'Azure Services' initialization code

### ISSUE THREAD

**Issue by peterbom** [Azure/vscode-aks-tools#130]
When the extension is loaded, it executes some code which initializes the 'Azure Services' treeview item:
<img width="98" alt="image" src="https://user-images.githubusercontent.com/1817696/168179488-cacb23ef-ba6c-4805-b069-fdff0894569e.png">

There are some things that need looking at with this:
- It is not documented, AFAIK -- @Tatsinnit - am I wrong about that?
- It doesn't appear to work, at least for me (as shown in the screenshot, there is nothing inside when you expand it).
- It can slow down extension loading a *lot* if the active cluster has a lot of CRDs.

I'm not sure, but I *think* the intended functionality behind it is already covered by the 'Custom Resources' item (the difference being that 'Azure Services' is filtered so that it only includes Azure/ASO custom resources).

Things to consider:
- Is my understanding correct?
- If working, would the 'Azure Services' list provide value to users beyond that of the 'Custom Resources' item?
- If we really want that functionality, could we retrieve it from the Kubernetes extension, rather than repeating the same, expensive `kubectl get crd` operations?
- If users can survive without this, can we remove the code and vastly decrease initialization time?

**Comment by itowlson** [comment]
Background:

This was created partly to provide a list of specifically Azure services, so the user could find them without grovelling through the full list of CRDs, but also as a place where people could pin the CRDs they regularly worked with, because, even filtered, the set of Azure CRDs is unmanageably huge!

This is not to say it can’t be removed or changed!  Just providing context on the reason it was done back in the day.

**Comment by peterbom** [comment]
Thanks @itowlson! @Tatsinnit also gave me a bit of history and I now have a much better understanding of why it's there.

I'm wondering if it might be possible for us to create a `NodeContributor` that wraps and filters the one that's registered for `Custom Resources`, rather than duplicating it (and all the long-running retrieval logic) in the AKS extension.

Any initial thoughts whether it might be worth pursuing that idea?

**Comment by itowlson** [comment]
That sounds like a good idea - loading a particular set of CRDs and representing them in a more relevant way is definitely a key use case for the API, and it would be great to have additional support for this.

**Comment by peterbom** [comment]
I've played around with a couple of ideas here, with pretty limited success. The API [provides a couple of ways](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/docs/extending/clusterexplorernodes.md) of initializing a folder:
1. Using `explorer.nodeSources.groupingFolder("Grouping Folder", undefined, resourceFolders)`, which makes use of resources that have been determined up-front during initialization.
2. Register a class implementing `NodeContributor`, which provides a `getChildren` method to be invoked when needed.

The bottleneck here is determining what the resources _are_ (by listing and filtering dozens of CRDs). Given that the API is clearly designed with performance in mind (`getChildren` being invoked lazily), it feels wrong to be using the first approach (as we are at the moment).

I _thought_ it might be possible to implement `NodeContributor` in such a way that it could lazily traverse the explorer nodes and extract the resource types from the `Custom Resources` folder children (depending on whether those resources are already loaded, that would populate-and-read -- or just read -- them). But even after subverting the public API by casting to internal types, I was unable to find a way to reuse the previously-determined resource types. At best, I ended up executing the existing `getChildren` multiple times. So I abandoned that approach; it'd be better to just re-implement the CRD retrieval logic from the Kubernetes extension.

A second thought I had was that we could implement `NodeContributor` using the [JS K8s client library](https://github.com/kubernetes-client/javascript), which might provide some performance benefits over invoking the `kubectl` binary. The problem I ran into here was that the Kubernetes extension doesn't appear to expose the kube config. I was hoping it might instead have been accessible from the cluster explorer somehow, but again I had to delve deep within the internals (`kubectl.api.kubectl.context.shell.execOpts().env.KUBECONFIG`), to hack it out. So that approach doesn't sound very promising either.

@itowlson - "loading a particular set of CRDs and representing them in a more relevant way is definitely a key use case for the API" -- this sounds like a really useful thing for us, but I'm not sure how to make it happen. Is your suggestion that we add it to the API of the Kubernetes extension in some way? If so I'd be happy to help in any way I can, but would need some guidance.

**Comment by itowlson** [comment]
We expose the kubeconfig path we're using via the Configuration interface: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/src/api/contract/configuration/v1_1.ts

However, hopefully we can make that a last resort.  Here are some thoughts on the API approaches:

* As you note, the built-in `GroupingFolder` currently needs to know its children at construction time.  We could explore ways to make this more dynamic if that would meet your needs?  In theory, that should just involve providing a callback to populate the list of resource types, instead of an array, but that code is a little tense with mapping back and forth from the API world.  Very happy to provide pointers and/or help if that seems like a promising way to go.
* A custom `NodeContributor` would indeed need to get its own list of items to display.  You can't currently re-use items from elsewhere in the tree.  Normally this isn't a huge issue - it's not ideal but it's not slower than other nodes.  So yeah you end up somewhat reimplementing the load logic.  We can look at exposing that or some of the mechanisms thereof - it used not to give you very much but I seem to recall Luca and contributors have done some work on optimising it now?  Again, very happy to explore that with you.

Thanks heaps for the detailed feedback - hope this is sufficient response and do let me know if you want more info or it's not clear!

**Comment by itowlson** [comment]
Sorry, re your last paragraph - it is the _intention_ that the API make this feasible already - but clearly it is not doing enough.  I think part of the trouble is that we have a blunt API (GroupingFolder/ResourceFolder) that is built mainly around "just put my four resource types in a folder", and a low-level API (NodeContributor) that is full customisation, anything goes, and nothing in between...

**Comment by peterbom** [comment]
Thanks, @itowlson! I think that gives a good path forward.

After my last post, I was already leaning towards your second bullet point (writing a custom node contributor). I'm pretty familiar with the CRD listing logic in the K8s extension so should be good to get started with that.

If a dynamic `GroupingFolder` does at some point make its way into the API, we can always update the code later to use that instead. It's certainly not critical for now.

And thanks for the pointer about the kubeconfig path! Agree that's more of a last resort, but great to know it's there.
