### ISSUE TITLE
Kubectl Don't work for AAD Enabled clusters. 💡☕️

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/vscode-aks-tools#173]
**Describe the bug**
Kubectl Don't work for AAD Enabled clusters.

**Mention the platform you are using**
Mention what platform you are using (oss, vscode) and pick the corresponding label.

**To Reproduce**

* Go to any feature currently using `kubctl` like ` get all pods` for AAD Enabled cluster.
    * The command run will hang as `Longrunning kubectl...`

**Expected behavior**
It should display all the pods under namespaces.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC O/S
 - Version - 1.73

**Additional context**
Need to discuss how we can fix the interactive AAD scenario here.

**Comment by mrafsyam** [comment]
Seconded this. 

Running any kubectl command, you'll get something like this for a long time
![image](https://user-images.githubusercontent.com/6120781/201244006-0f4cac70-deaf-4065-8b24-c44abf5fabf2.png)

Eventually, this failed

**Comment by Tatsinnit** [comment]
☕️☕️ The key of this issue is the behind the scenes stuff, for AAD Auth clusters, so if we keep this long running for a while, this happens: (It happening because behind the scene auth has interactive mode and this all appears once the token expires.)

<img width="582" alt="Screenshot 2022-11-11 at 8 29 18 PM" src="https://user-images.githubusercontent.com/6233295/201289378-9d04e5b9-5fbc-40b7-8793-8ed2543feb14.png">

**Comment by peterbom** [comment]
Some notes after a bit of experimentation and discussion with @Tatsinnit...

Some background detail on the existing implementation: we download a temporary `kubeconfig` file for each run of the command. This is why it happens for every invocation of a`kubectl` commands, rather than using any cached tokens that might exist in users' `.kube` directories.

Ideally, we want to avoid forcing the user to perform an interactive login, because that would involve either directly putting the user into a command prompt (unexpected UX), or letting the extension interact with `stdout`/`stdin` of an external process, which is complex, fragile, and fraught with edge cases.

**What is really happening with interactive login?**
Other than local accounts (not applicable to AAD clusters), AKS supports two 'formats' of authentication plugins in `kubeconfig` files: `azure` and `exec`:
- The `azure` format inserts an `auth-provider` section into the `kubeconfig` for the user, containing metadata about authentication configuration but no actual credentials. The first time a `kubectl` command is run, the `azure` plugin populates the access token, refresh token and expiry time directly in the `kubeconfig` file.
- The `exec` format inserts an `exec` section into the `kubeconfig` file. This causes `kubectl` to invoke an executable binary with specified arguments. For AKS, it runs `kubelogin get-token --login devicecode ...` (with extra arguments identifying server and client). For this, the binary (`kubelogin`) is responsible for storing/using cached credentials.

**How might we make it non-interactive?**
1. Use JS libs to generate an access token which we use to update the `auth-provider` for the `azure` plugin directly from the extension. Problem: the `azure` plugin is deprecated and will be unavailable in K8s v1.25+.
2. Use `kubelogin` to convert the `kubeconfig` file to an `exec` format which runs `kubelogin get-token --login azurecli ...`. This would make use of users' authenticated `az` CLI session to avoid the interactive login. This would require checking whether `az` is installed (as it's too heavyweight to take a hard dependency on), and even if it is installed it could still fall back to interactive login if the user is not logged in, or the session is expired (possibly worse, the *wrong* user could be logged in).
3. Download the `kubeconfig` file using the `exec` format, and use JS libs to generate an access token which we store in a temp file, in the JSON format used by the `kubelogin` cache. We can add an extra argument to the `exec` command: `kubelogin get-token --token-cache-dir <token dir>`. This should force `kubelogin` to use the supplied token, rather than performing an interactive login.

At this stage (3) looks most promising, although I haven't yet verified whether it'll actually work.... I'll do some experimentation and post updates here.

**Comment by Tatsinnit** [comment]
Thank you so much @peterbom and yes absolutely on-point from the discussions. ☕️ ❤️

💡 🐈 Just to also add a step back thinking we did at first: is that do we want to handle the AAD Scenario and then we agree that this makes sense as the k8s recommendation is now to use AAD.

**Option:3** - Seems progressive and it will help in kubernetes extension when this behavior will start showing up more widely for AAD cluster, currently local account is the default chosen `access option` we could use this existing place in parent extension for AKS to download `kubelogin` => `.vs-kubernetes/` https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/src/components/config/config.ts#L148 

Thanks heaps and gentle fyi to @squillace, @itowlson and @gambtho 💡☕️ ❤️ + @rzhang628

**Comment by squillace** [comment]
AAD is _by design_ hard to automate, so no one should think this is a failure scenario. In addition, if we actually DID do a pop up window in VS to do the creds/auth dance, no one would have a problem -- this is the same experience that anyone would have using aad creds (WSL does pretty much this and it's just required). 

Now, all that said, if you think way 3 is easier and less awkward, go for it. @itowlson or @rzhang628 may have insight into the work entailed.

**Comment by rzhang628** [comment]
Second on this. 
Use VS Code (version 1.73.1). 

Reproduce:
1. go to AKS extension, right click Run kubectl commands, 
2. try to run any of the commands: get all events, all pods, API resources, Cluster Info or Nodes
3. the command runs forever

Screenshots: 
<img width="308" alt="image" src="https://user-images.githubusercontent.com/69864647/202040689-67a07e61-10da-4f5f-9f33-52dcda362922.png">

Desktop:
OS: Windows 11 Enterprise
Browser: Microsoft Edge Version 107.0.1418.42 (Official build) (64-bit)

**Comment by Tatsinnit** [comment]
❤️☕️🙏 Thank you all for the kind discussions under this issue, we have made relevant changes and they are released as part of `1.3.7`, closing this issue
