### ISSUE TITLE
Activation failure: Cannot find module 'vscode-kubernetes-tools-api'

### ISSUE THREAD

**Issue by daniv-msft** [Azure/vscode-aks-tools#18]
The vscode-aks-tools extension failed to activate for one of our team members with error:
`Activating extension 'ms-kubernetes-tools.vscode-aks-tools' failed: Cannot find module 'vscode-kubernetes-tools-api'`

![image](https://user-images.githubusercontent.com/48293037/71485382-9a5c4400-27c5-11ea-8560-4d108c791446.png)

The team member fixed this by uninstalling the extension, deleting the files locally (`%UserProfile%\.vscode\extensions\ms-kubernetes-tools.vscode-aks-tools-0.0.4`) and then reinstalling the extension.
Just uninstalling and reinstalling wasn't sufficient to fix the issue.

Is this something you've already seen?

**Comment by Tatsinnit** [comment]
Hiya @daniv-msft , I have not seen this and probably this was **caused with corrupt or partial extension install could be for various factors**. Also, cc: @itowlson for more ideas but seems like this was due to a dependency missing caused by unknown partial extension download reason.

The one way I can replicate this (not exactly) but close is by first `npm uninstall vscode-kubernetes-tools-api` and then try and build it which will give me the module `cannot find module vscode-kubernetes-tools-api`. 

In case there is more consistent replication, I think we can close this with the premise that it could be caused by partial extension download.

**Comment by daniv-msft** [comment]
Hi @Tatsinnit,
Thank you for having a look at this. I haven't seen this bug reproduce since this initial issue, so it's fine to close it for now, and reopen it in the future if needed (hopefully with better repro steps).
