### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by smrtRock** [Azure/vscode-aks-tools#21]
- Issue Type: `Bug`
- Extension Name: `vscode-aks-tools`
- Extension Version: `0.0.4`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by itowlson** [comment]
@smrtRock Looks like some of the issue details didn't come through - can you remember what the problem was?  Thanks!

**Comment by Tatsinnit** [comment]
Hiya @smrtRock , seems like the details of the issue didn't come through, and since its more than 5 months I will close this issue for now as there is no actionable item we can investigate, but happy for you/anyone to reopen in case there are more details relevant to this issue. Thanks heaps,

cc: @itowlson
