### ISSUE TITLE
Garbage collection on AKS Nodes

### ISSUE THREAD

**Issue by sprab** [Azure/vscode-aks-tools#288]
It would be great to have an extension to manually trigger garbage collection within an aks node.
This would be useful when there is disk pressure due to insufficient space or the disk space getting filled up with the unused images.

**Comment by Tatsinnit** [comment]
This is super @sprab, 🎊🙏 Thank you for this! Would you be willing to please share how it is done currently, so that we can stop eat underlying work required and see how we can make it as one-click and also to iron out any possible challenges to brainstorm with you.

cc: and fyi for visibility for @peterbom , thank you

**Comment by Tatsinnit** [comment]
for documentation reasons:

* https://eraser-dev.github.io/eraser/docs/quick-start
* https://learn.microsoft.com/en-us/azure/aks/image-cleaner

**Comment by Tatsinnit** [comment]
❤️☕️🙏 Thank you @sprab ,   A quick loop back on this 🚀 I have a POC for this sceanario https://eraser-dev.github.io/eraser/docs/quick-start#automatically-cleaning-images , I guess it will be great phase 1 and at least provide users to have this available for the users, although I also see in vanilla kuberentes kubelet have the https://kubernetes.io/docs/concepts/architecture/garbage-collection/#image-maximum-age-gc


I see eraser is written by our upstream team, it seems very feasible path to add this in, will share the vsix with you. Thank you.
