### ISSUE TITLE
Implement new designs for cluster create page

### ISSUE THREAD

**Issue by qpetraroia** [Azure/vscode-aks-tools#294]
Implement the new designs for the cluster create page based off of @ivelisseca's feedback.

Requirements:
- Clusters are created via design presets
     - Cluster specs match the presets that are defined in the Azure Portal
- Location of the resource group is used for the location of the cluster
     - If there is an issue, default to EastUS
 - AKS version defaults to the current default AKS version available on the latest patch
     - If the API call fails, in the error message output, link to the Azure Portal asking the user to create the cluster there

**Comment by peterbom** [comment]
Some design/implementation notes:
- The presets are supposedly 'fixed', but in reality they will almost certainly change over time. Newer SKUs will be introduced and cluster features and best practices will evolve.
- This will mean periodically revisiting this work, and ensuring we are consistent with the Portal.
- The easiest way I can see to compare functionality between the Portal and the extension is to view a diff between the ARM templates generated by the Portal and those used by us (they can be stored as source-controlled resources in our repo).
- _Partly_ for that reason I'd prefer to use ARM templates to define the resources we're creating, rather than doing it via the JS SDKs for each resource.
- ARM templates also have [other benefits](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/overview#why-choose-arm-templates), particularly the repeatability and declarative nature which I think would ease recovery from errors resulting in partially deployed state.

Some challenges and discussion points for this:
- Some parameters (we've identified K8s version so far) will change rapidly over time, so we will need to determine those dynamically when we run the deployment. K8s version is dependent on subscription and region, which are already specified by users, so this should be straightforward using the [JS SDK](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list-kubernetes-versions?view=rest-aks-2023-08-01&tabs=JavaScript).
- Capabilities of resources depend on region and zones. For example `Standard_D8ds_v5` is not allowed in all zones in southeastasia.
- The Portal deals with the above issue by extensively validating the entire tree of resources and allowing the user to make changes. We can't do that without effectively re-implementing the entire Portal UX. So we'd need to make some choices: allow the user to proceed and report errors back to them? Or validate and ask them to choose a different region?
- Depending on the user's permissions on the selected subscription, they may not have permission to deploy some resources. For example, when deploying a production-standard cluster with monitoring, the resources include an administrator role, which I think can only be deployed by a user with Owner permissions on the subscription. Can we validate that? Can we filter the subscriptions that will work? Do we ignore the problem and just report errors back to the user when things fail?
- The Portal deploys different resources for the same preset depending on the subscription chosen. We've noticed this for the monitoring resources. Sometimes the Portal will decide to create new workspaces and Prometheus/Grafana resources, and sometimes it won't. We'll need to understand the reasoning behind this. It might be hard to predict what users would want here, because we won't know enough about their circumstances to decide whether we should use an existing workspace (if they have one) or create a new one. We could have some dedicated UX to help guide and question them about this decision (which would be an improvement on the Portal experience), or we could simply say we're not going to create monitoring resources and link them to some guidance for adding those themselves (if they've selected a preset that includes monitoring).
- If we were to deploy monitoring resources ourselves, the original plan of copying ARM templates from the Portal and storing them as resources would be a large maintenance burden. The reason for this is that the Portal-generated templates for monitoring resources are not parameterized (unlike the cluster resource). In other words, each of the 12 extra resources in the template contain hard-coded subscription, resource group and cluster name strings, and would hence be unusable for anyone except the person who generated them. We'd have to either go through them manually and templatize them (not just now, but in the future when we're maintaining this and think the presets might have changed), or revert to creating these resources individually through SDKs, resulting in a confusing hybrid approach where it's hard to reason about the behaviour, and hard to view/compare history.

**Comment by Tatsinnit** [comment]
Just archiving most of the chat around how the dynamic `kubernetesVersion`,  - https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list-kubernetes-versions?view=rest-aks-2023-08-01&tabs=JavaScript  - Unless anyone else have has better idea:

Once this gives lis of kubernetes verion, we have no har dependency and all hunky dory, jsut some thoughts.

**Here is the API.**

```*.ts
 const result = await client.managedClusters.listKubernetesVersions(location);
```
 


**To make it more clear**


💡 We have all the attributes in need for this funct call at the repo level with examples.

```*.ts
const { ContainerServiceClient } = require("@azure/arm-containerservice");
const { DefaultAzureCredential } = require("@azure/identity");
async function listKubernetesVersions() {
  const subscriptionId = process.env["CONTAINERSERVICE_SUBSCRIPTION_ID"] || "subid1";
  const location = "location1";
  const credential = new DefaultAzureCredential();
  const client = new ContainerServiceClient(credential, subscriptionId);
  const result = await client.managedClusters.listKubernetesVersions(location);
  console.log(result);
}
```


**Pros:**

- This will atleast take a year to deprecate and we already do with other tools and keep them inline with the version those tool use.
- More certain, easy to test and less uncertainity.
- More from the source of truth and nothing hardcoded


### Error Handle API Failure Is Best Move

If API for some reason fails then it means issue is with API and we should safely `errorable` our code for those reasons, because if `list` operation from sdk fails then surely `create` will fail. (These failures at SDK level is above layer and we should be deterministic to these failures and error handle with same certainty. Please don't misunderstand this with, I am canvassing for no **retry** but this is basically clean path for sdk and error-handling. If anyone has further `retry` idea this is great place to share or internal channel) 

Very excited to see this new U/X coming into life.

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGw0YWl2ZzZ5dDE0bXp2dDMweGF5YnljaTRqbTVzMDQ5b3p5M3d6dyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l2QDUZ7ZDAnGAhane/giphy.gif)

**Comment by hsubramanianaks** [comment]
Currently we are proceeding with one preset Dev/Test matching with portal and see how users/developers like this. Agreed there are challenges with ARM templates parameterizing and handling error/exception cases. Adding to @peterbom points there are few more to this 

1. When using ARM templates and when error happens due to one of the resources, we need to get inner exception from deployments response. 
2. Also some of the parameters requires validations ex: nodeResourceGroup should not be greater than length 80 characters - [link here](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/aks-common-issues-faq#what-naming-restrictions-are-enforced-for-aks-resources-and-parameters-). Since we are going towards ARM templates to match with portal, we need to know how portal is dealing with this.
