### ISSUE TITLE
[Known Issue] ContainerNotFound error code returned when generating downloadable links

### ISSUE THREAD

**Issue by yunjchoi** [Azure/vscode-aks-tools#44]
Due to a limitation in the underlying tool, AKS Periscope, you may **occasionally** encounter an error message similar to below when you click on the Generate Link Button for the first time.

`Error generating downloadable link: RestError: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist. RequestId:ec6f38a9-001e-008b-471e-9638f2000000 Time:2020-09-29T05:07:07.3726564Z</Message></Error>`

This is due to AKS Periscope not handling the storage API latency and is captured here: https://github.com/Azure/aks-periscope/issues/30. Future enhancements are planned to address this issue in the tool. Also, you can refer to this PR for further details on tool level challenges: https://github.com/Azure/vscode-aks-tools/pull/33

**Current workaround is to retry by clicking the Generate Link Button again after waiting for ~5 minutes.** You will see the downloadable and shareable links for the collected logs.

**Comment by Tatsinnit** [comment]
💡 Thanks for this and since this issue is open for a while, I think I will close it as it since real issue is with how azblob upload function behave which is  used in periscope tool. Prima facie, the upload function in blob does 256 mb data at once and it is non asynchronous funct so no await et. Al. 

read comments just above the upload code.

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-go?tabs=linux#upload-blobs-to-the-container

I will close this for now in case of anything specific we can reopen this.

Thank you so much 🙏☕️
