### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by abdelhajji** [Azure/vscode-aks-tools#45]
- Issue Type: `Bug`
- Extension Name: `vscode-aks-tools`
- Extension Version: `0.0.7`
- OS Version: `Windows_NT x64 6.1.7600`
- VSCode version: `1.49.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by itowlson** [comment]
Kia ora @abdelhajji, it looks like the details you wrote into VS Code didn't paste.  Could you update the issue with a description and more information please?

**Comment by Tatsinnit** [comment]
Hiya @abdelhajji , seems like the details of the issue didn't come through, and since its more than 2 months I will close this issue for now as there is no actionable item we can investigate, but happy for you/anyone to reopen in case there are more details relevant to this issue. Thanks heaps,

cc: @itowlson
