### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by KYZITEMELOS93** [Azure/vscode-aks-tools#50]
- Issue Type: `Bug`
- Extension Name: `vscode-aks-tools`
- Extension Version: `0.0.8`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.51.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Tatsinnit** [comment]
Hi @KYZITEMELOS93 , it looks like the details you wrote into VS Code didn't paste. Could you update the issue with a description and more information please? Thanks

**Comment by Tatsinnit** [comment]
Hiya @KYZITEMELOS93  , thought I might do some end of year clean up seems like the details of the issue didn't come through, and since its more than 1 month I will close this issue for now as there is no actionable item we can investigate, but happy for you/anyone to reopen in case there are more details relevant to this issue. Thanks heaps,

cc: @itowlson

**Comment by KYZITEMELOS93** [comment]
oops sorry I don't remember doing this must have been automatic my apologies!
