### ISSUE TITLE
Provide a stable, documented API

### ISSUE THREAD

**Issue by itowlson** [Azure/vscode-aks-tools#8]
Some people have expressed interest in integrating their own Azure extensions with the AKS cluster browser.  At the moment this requires reading source code and making assumptions about internal data structures, which isn't sustainable: let's provide a simple API that we can stabilise, document and evolve in a compatibility-preserving way.

cc @squillace

**Comment by Tatsinnit** [comment]
💡☕️ Since this is the only issue under this repo, I wonder if this is all no longer required because I can see how easy it is for other extensions to add features like Pipeline folks did. Also not sure what is the key intent / idea for this.

What do you guys think, and what exactly this work entails, et. al. is not something I know hence a N00b questions. :) Is it cool to close this for now, if this is no longer needed. 

Thanks heaps, 🐳 🙏 🎄

**Comment by itowlson** [comment]
This harks back to the work with other Azure teams that wanted to surface their services in the Cloud tree.  I think you can probably put it on ice, but perhaps make sure there are comments in the code that other Azure teams have taken dependencies on the Cloud tree node objects, and that compatibility must be considered when modifying them.

**Comment by Tatsinnit** [comment]
Thank you so much for this @itowlson, will this #94 will suffice. Please let me know what you think 🙏☕️ and thank you once again for quick replies and context. ☃️

**Comment by Tatsinnit** [comment]
☕️❤️💡 Thank you so much @itowlson for discussions and pointers around this, closing this workitem and if need be we can either re-open this or open a new one with whatever underlying work which should be involved. 

for archive: here is the comment and location of the files under following comments: https://github.com/Azure/vscode-aks-tools/pull/94#issuecomment-1000580377 

Thanks heaps. 🙏
